GET http://localhost:3002/users/10682df34705150f05fa125e
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjgyZGYzNDcwNTE1MGYwNWZhMTI1ZSIsImxvZ2luIjoiYWRtaW4iLCJyb2wiOiJhZG1pbiIsImlhdCI6MTYxNzQ4NjQ4MX0.PsEnoygPyQTMdptIYzqB0b93cPNxayBbeVVsvAu0l7GHGIUSiEx5FQ08coDUmWStjHVxDTL0TJBJk9DUyCgoRA