POST http://localhost:3002/meals
Content-Type: application/json

{
  "name" : "Ensalada de col",
  "type": "lunch",
  "ingredients": [
    "col",
    "queso",
    "manzana",
    "mahonesa casera"
  ],
  "calories": [{
      "carbohydrates" : 66,
      "proteins" : 66,
      "fats" : 66
  }]
}