PUT http://localhost:3002/meals/60674b945fa38c3aa496a13b
Content-Type: application/json

{
  "name" : "Ensalada de col con manzana",
  "type": "lunch",
  "ingredients": [
    "col",
    "queso",
    "manzana",
    "mahonesa casera",
    "amor"
  ],
  "calories": [{
      "carbohydrates" : 66,
      "proteins" : 66,
      "fats" : 66
  }]
}